# Generated by Django 4.1.1 on 2023-12-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_gs_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsservice',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='goodsservice',
            table='make_gs_list_goodsservice',
        ),
    ]
