# Generated by Django 4.1.1 on 2023-12-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('jname', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=2)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='EstimateInfo',
            fields=[
                ('cname', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('cls_num', models.CharField(max_length=2)),
                ('mark', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'estimate',
            },
        ),
    ]
